[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
# multiline_func_header = 'params_first'
quote_style = 'single'
number_underscore = 'thousands'
wrap_comments = false

[profile.default]
src = "src"
out = "out"
lib = "lib"

[rpc_endpoints]
gnosis = "https://rpc.gnosis.gateway.fm"
optimism = "https://mainnet.optimism.io"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
